[PHP]
zend.exception_ignore_args = On
zend.exception_string_param_max_len = 0
expose_php = Off
max_execution_time = 30
max_input_time = 60
memory_limit = 128M
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
post_max_size = 100M
file_uploads = On
upload_max_filesize = 20M
max_file_uploads = 20

[Session]
session.save_handler = files
session.serialize_handler = php

[APCu]
apc.enabled = 1
